/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
    ElCard: (typeof import('element-plus/es'))['ElCard']
    ElDescriptions: (typeof import('element-plus/es'))['ElDescriptions']
    ElDescriptionsItem: (typeof import('element-plus/es'))['ElDescriptionsItem']
    ElImage: (typeof import('element-plus/es'))['ElImage']
    ElPagination: (typeof import('element-plus/es'))['ElPagination']
    ElTableV2: (typeof import('element-plus/es'))['ElTableV2']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
