/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
    ElCard: (typeof import('element-plus/es'))['ElCard']
    ElDescriptions: (typeof import('element-plus/es'))['ElDescriptions']
    ElDescriptionsItem: (typeof import('element-plus/es'))['ElDescriptionsItem']
    ElImage: (typeof import('element-plus/es'))['ElImage']
    ElPagination: (typeof import('element-plus/es'))['ElPagination']
    ElTableV2: (typeof import('element-plus/es'))['ElTableV2']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    List: typeof import('./src/components/List.vue')['default']
    ListContainer: typeof import('./src/components/ListContainer.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    ListPagination: typeof import('./src/components/ListPagination.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PaginationSection: typeof import('./src/components/PaginationSection.vue')['default']
    PokemonDisplay: typeof import('./src/components/PokemonDisplay.vue')['default']
    PokemonListItem: typeof import('./src/components/PokemonListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowItem: typeof import('./src/components/RowItem.vue')['default']
  }
}
